name = "duolb"
main = "./dist/_worker.js"
compatibility_date = "2026-01-20"

[build]
command = "npm run build"

[vars]
PUBLIC_SUPABASE_URL="https://snztglegyyenrrdgsnvt.supabase.co"
PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuenRnbGVneXllbnJyZGdzbnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MzY5MjgsImV4cCI6MjA4NTAxMjkyOH0.3ydxyu1J3VRSjKH7i6Eg53eiW4FS3Itfu_-D90i8oIo"
