name = "duolb"
main = "./dist/_worker.js"
compatibility_date = "2026-01-20"

[build]
command = "npm run build"

[vars]
PUBLIC_SUPABASE_URL=https://snztglegyyenrrdgsnvt.supabase.co
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuenRnbGVneXllbnJyZGdzbnZ0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTQzNjkyOCwiZXhwIjoyMDg1MDEyOTI4fQ.SGtzE5IstFMCDNdif6-jVtPL-6hy7YRHE3tUZOD2tlo
PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuenRnbGVneXllbnJyZGdzbnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MzY5MjgsImV4cCI6MjA4NTAxMjkyOH0.3ydxyu1J3VRSjKH7i6Eg53eiW4FS3Itfu_-D90i8oIo
